language: rust
sudo: false
rust: nightly
dist: trusty

env:
  - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3"

matrix:
  include:
    - rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl DEPLOY=1 OPENSSL_STATIC=1
      before_script:
        - rustup target add $TARGET
        - curl https://www.openssl.org/source/openssl-1.0.2o.tar.gz | tar xzf -
        - (cd openssl-1.0.2o &&
          CC=musl-gcc ./Configure --prefix=$HOME/openssl-musl no-dso no-ssl2 no-ssl3 linux-x86_64 -fPIC &&
          make -j$(nproc) &&
          make install)
        - export OPENSSL_DIR=$HOME/openssl-musl
      script: cargo build --release --target $TARGET

    - os: osx
    - os: osx
      env: MACOSX_DEPLOYMENT_TARGET=10.7 DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=1
      script: cargo build --release --target $TARGET

addons:
  apt:
    packages:
    - musl-tools

script:
  - cargo test

before_deploy:
  - name="ghshare-$TRAVIS_TAG-$TARGET"
  - cp target/$TARGET/release/ghshare $name

deploy:
  api_key:
    secure: IYHl88KWV1VxxPksrGRdLZbtY+b1lxDDAKYOwmZisgzeX7XozoJoiwJYbopRE6T/4MAzGBpAzpuabG52GKwnXrxMHYVneHWMjHF6Tw1P5kddpH/H4+RQvSd8D4R+AyMRIFR4lEFlr3n6zRw8e3DYIkXOWSPR4P1lYWwqu980FSaoHIJV+2CBh6//oup2Zwc6xOuZoXsYhRputf6q0zb1tEiO0EoU9u1j2bHG33uZau1Rc1m9UvHnQXWKrGwMPwhl+XN+srgLAjUw0psve+pkuc6TmVOwJ+fRGfp6O0g9uSugW/MQKPvC95vzmdcDvAmSYnRwaoSTFOgeygboZIn2eTG0lC/T6/acqpPOD8ynVJuWDeRXsOdAmsgiAhskD2vVTXRRosHP2bTHOXLNlDwZO+RO7T7Do3TwIf6hqL818n5hony1HGOIbIm2WXJS8AkKaN4gno+Yf16pjqMfgDophX2tv9puUJ20x2m2J099pnji7UF0SOIhnNvNxRGzzgy97SZZO+f96/pS4ecIPO2psKCd86s8UeHVkswAw6eXT9HLB/qh+GRfttwSS3LGmNWYejZrBKBFwDElPG9fMHNjFRaG4nXZEXqfOzKzx/NBZD6sxufCR/7p1hAy76T+rR+XaIjdkGTDjxl7UsjBsprfLLC5kzb9RQc8OMV7hhp+Bxk=
  file_glob: true
  file: ghshare-$TRAVIS_TAG-$TARGET
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
