language: rust
sudo: false
rust: stable
dist: trusty

services:
  - docker

matrix:
  include:
    - env:
        - DEPLOY=1
        - TARGET=x86_64-unknown-linux-musl
      before_script:
        - docker build -t ghshare .
        - docker run -v $(pwd):/tmp/src --entrypoint=cp ghshare -r /src/target /tmp/src/.
      script: docker run --entrypoint=cargo ghshare test --release --target $TARGET
    - os: osx
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.7
        - DEPLOY=1
        - TARGET=x86_64-apple-darwin
        - OPENSSL_STATIC=1
        - SODIUM_STATIC=1
        - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3"
      before_script:
        - cd ..
        - curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.17.tar.gz | tar xzf -
        - cd libsodium-1.0.17
          && ./configure --prefix=$HOME/libsodium --enable-shared=no
          && make -j$(nproc)
          && make install
        - export PKG_CONFIG_PATH="$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH"
        - cd ../ghshare
        - cargo test --release --target $TARGET
      script: cargo build --release --target $TARGET

before_deploy:
  - name="ghshare-$TRAVIS_TAG-$TARGET"
  - cp target/$TARGET/release/ghshare $name

deploy:
  api_key:
    secure: IYHl88KWV1VxxPksrGRdLZbtY+b1lxDDAKYOwmZisgzeX7XozoJoiwJYbopRE6T/4MAzGBpAzpuabG52GKwnXrxMHYVneHWMjHF6Tw1P5kddpH/H4+RQvSd8D4R+AyMRIFR4lEFlr3n6zRw8e3DYIkXOWSPR4P1lYWwqu980FSaoHIJV+2CBh6//oup2Zwc6xOuZoXsYhRputf6q0zb1tEiO0EoU9u1j2bHG33uZau1Rc1m9UvHnQXWKrGwMPwhl+XN+srgLAjUw0psve+pkuc6TmVOwJ+fRGfp6O0g9uSugW/MQKPvC95vzmdcDvAmSYnRwaoSTFOgeygboZIn2eTG0lC/T6/acqpPOD8ynVJuWDeRXsOdAmsgiAhskD2vVTXRRosHP2bTHOXLNlDwZO+RO7T7Do3TwIf6hqL818n5hony1HGOIbIm2WXJS8AkKaN4gno+Yf16pjqMfgDophX2tv9puUJ20x2m2J099pnji7UF0SOIhnNvNxRGzzgy97SZZO+f96/pS4ecIPO2psKCd86s8UeHVkswAw6eXT9HLB/qh+GRfttwSS3LGmNWYejZrBKBFwDElPG9fMHNjFRaG4nXZEXqfOzKzx/NBZD6sxufCR/7p1hAy76T+rR+XaIjdkGTDjxl7UsjBsprfLLC5kzb9RQc8OMV7hhp+Bxk=
  file_glob: true
  file: ghshare-$TRAVIS_TAG-$TARGET
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
